{% set name = "jupyter-secrets-manager" %}
{% set version = "0.4.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_secrets_manager-{{ version }}.tar.gz
  sha256: 518af21820d1a8bf26b2903d8765031b35694f03ee1299fefb317a20a410bac0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatch-jupyter-builder >=0.5
    - hatchling >=1.5.0
    - jupyterlab >=4,<5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyter_secrets_manager
  requires:
    - python {{ python_min }}
    - jupyterlab >=4,<5
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyter-secrets-manager.*OK.*(python, jupyter_secrets_manager)"

about:
  home: https://github.com/jupyterlab-contrib/jupyter-secrets-manager
  summary: A JupyterLab extension to manage secrets.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brichet
    - jtpio
